### ISSUE TITLE
Issue in Rails 4.2 with modify frozen ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by wldcordeiro** [SCPR/secretary-rails#13]
It appears there were changes in rails 4.2 that are causing this gem to not work.

The error is in dirty_associates line 51 according to the traceback.

```
can't modify frozen ActiveSupport::HashWithIndifferentAccess
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/hash_with_indifferent_access.rb:97:in `[]='
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/hash_with_indifferent_access.rb:97:in `[]='
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/secretary-rails-1.1.1/lib/secretary/dirty_associations.rb:51:in `roles_will_change!'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/secretary-rails-1.1.1/lib/secretary/dirty_associations/collection.rb:51:in `prepare_to_change_association'
```

**Comment by bricker** [comment]
@wldcordeiro Thanks for reporting this. I'll see if I can push 4.2 support this weekend.

**Comment by wldcordeiro** [comment]
@bricker any luck with the 4.2.0 support?

**Comment by bricker** [comment]
Thanks for following up, I'm working on this today.

**Comment by bricker** [comment]
Hi @wldcordeiro , I have pushed https://github.com/SCPR/secretary-rails/commit/7c5efddf5b1b3b0a8bc1dff21facc13f2b7595e3 to fix this and released [`2.0.0.rc1`](https://rubygems.org/gems/secretary-rails/versions/2.0.0.rc1). Please give it a try and let me know if it works for you. I'll do an official `2.0.0` release in a week or so if there are no issues.

Thanks!

**Comment by wldcordeiro** [comment]
Cool thanks. I'll test it out and give you a heads up. :smile: Good to see the quick turn around time.

**Comment by wldcordeiro** [comment]
@bricker The RC is working great, no issues on Rails 4.2.0.

**Comment by bricker** [comment]
Great! Glad to hear it. Thanks for opening the issue, I'm not using this library with any 4.2 apps at the moment so I wouldn't have caught it.

**Comment by wldcordeiro** [comment]
@bricker looks like there hasn't been any issues with the RC. You can probably push the final to rubygems now.

**Comment by bricker** [comment]
Thanks! [secretary-rails 2.0.0](https://rubygems.org/gems/secretary-rails/versions/2.0.0) is released.
